# Generated by Django 4.2.17 on 2025-01-20 19:15

import ailaq.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('is_psychologist', models.BooleanField(default=False)),
                ('wants_to_be_psychologist', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('communication_language', models.CharField(blank=True, choices=[('RU', 'Russian'), ('EN', 'English'), ('KZ', 'Kazakh')], max_length=2, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6, null=True)),
                ('about_me_ru', models.TextField(blank=True, null=True)),
                ('catalog_description_ru', models.TextField(blank=True, null=True)),
                ('help_text_ru', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('works_with', models.CharField(blank=True, choices=[('ADULTS', 'Взрослые'), ('TEENAGERS', 'Подростки'), ('CHILDREN', 'Дети'), ('FAMILY', 'Семья')], max_length=50, null=True)),
                ('problems_worked_with', models.TextField(blank=True, null=True)),
                ('work_methods', models.TextField(blank=True, null=True)),
                ('practice_start_date', models.DateField(blank=True, null=True)),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('psychologist_directions', models.TextField(blank=True, null=True)),
                ('child_psychologist_directions', models.TextField(blank=True, null=True)),
                ('coach_directions', models.TextField(blank=True, null=True)),
                ('additional_specialization', models.TextField(blank=True, null=True)),
                ('work_features', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('education_files', models.FileField(blank=True, null=True, upload_to='education_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_in_catalog', models.BooleanField(default=False)),
                ('purchased_applications', models.IntegerField(default=0)),
                ('expired_applications', models.IntegerField(default=0)),
                ('active_applications', models.IntegerField(default=0)),
                ('paid_applications', models.IntegerField(default=0)),
                ('unpaid_applications', models.IntegerField(default=0)),
                ('rating_system', models.FloatField(default=0.0)),
                ('internal_rating', models.FloatField(default=0.0)),
                ('session_duration', models.IntegerField(blank=True, null=True)),
                ('session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('session_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online_session_duration', models.IntegerField(blank=True, null=True)),
                ('online_session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online_session_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('couple_session_duration', models.IntegerField(blank=True, null=True)),
                ('couple_session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('couple_session_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('couple_online_session_duration', models.IntegerField(blank=True, null=True)),
                ('couple_online_session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('couple_online_session_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('office_photo', models.ImageField(blank=True, null=True, upload_to='office_photos/')),
                ('passport_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DOCUMENTS_REQUESTED', 'Documents Requested')], default='PENDING', max_length=20)),
                ('documents_requested', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('can_see_catalog', models.BooleanField(default=False)),
                ('can_see_quick_requests', models.BooleanField(default=False)),
                ('can_accept_requests', models.BooleanField(default=False)),
                ('can_edit_profile', models.BooleanField(default=False)),
                ('can_change_block_status', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('is_in_catalog', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ailaq.psychologistapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ailaq.clientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ailaq.psychologistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('psychologist_name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ailaq.clientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ailaq.psychologistprofile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ailaq.session')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=ailaq.models.get_default_cost, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='ailaq.psychologistapplication')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='education_documents/')),
                ('psychologist_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_documents', to='ailaq.psychologistapplication')),
            ],
        ),
        migrations.CreateModel(
            name='BuyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='ailaq.clientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='ailaq.psychologistprofile')),
            ],
        ),
    ]
