# Generated by Django 4.2.20 on 2025-04-05 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telegram_id', models.BigIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Telegram ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('verification_code_expiration', models.DateTimeField(blank=True, null=True)),
                ('is_psychologist', models.BooleanField(default=False)),
                ('wants_to_be_psychologist', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='education_documents/')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Год получения документа', null=True)),
                ('title', models.CharField(blank=True, help_text='Название документа', max_length=255, null=True)),
                ('file_signature', models.CharField(blank=True, help_text='Подпись к файлу', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('first_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('OTHER', 'Другой')], max_length=10, null=True)),
                ('communication_language', models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=10, null=True)),
                ('service_countries', models.JSONField(blank=True, default=list, help_text='Список стран приема')),
                ('service_cities', models.JSONField(blank=True, default=list, help_text='Список городов приема')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me_ru', models.TextField(blank=True, null=True)),
                ('catalog_description_ru', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('works_with', models.CharField(blank=True, choices=[('ADULTS', 'Взрослые'), ('TEENAGERS', 'Подростки'), ('CHILDREN', 'Дети'), ('FAMILY', 'Семья')], max_length=50, null=True)),
                ('problems_worked_with', models.TextField(blank=True, null=True)),
                ('work_methods', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж работы (в годах)')),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_specialization', models.TextField(blank=True, null=True)),
                ('additional_psychologist_directions', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('office_address', models.TextField(blank=True, null=True, verbose_name='Полный адрес офиса')),
                ('office_photo', models.ImageField(blank=True, null=True, upload_to='office_photos/')),
                ('service_sessions', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_in_catalog', models.BooleanField(default=False)),
                ('purchased_applications', models.IntegerField(default=0)),
                ('expired_applications', models.IntegerField(default=0)),
                ('active_applications', models.IntegerField(default=0)),
                ('paid_applications', models.IntegerField(default=0)),
                ('unpaid_applications', models.IntegerField(default=0)),
                ('rating_system', models.FloatField(default=0.0)),
                ('internal_rating', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DOCUMENTS_REQUESTED', 'Documents Requested')], default='PENDING', max_length=20)),
                ('documents_requested', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('education_files', models.ManyToManyField(blank=True, related_name='applications', to='ailaq.educationdocument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('can_see_catalog', models.BooleanField(default=False)),
                ('can_see_quick_requests', models.BooleanField(default=False)),
                ('can_accept_requests', models.BooleanField(default=False)),
                ('can_edit_profile', models.BooleanField(default=False)),
                ('can_change_block_status', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('telegram_id', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONTACTED', 'Психолог связался'), ('COMPLETED', 'Сессия проведена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuickClientConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Как к вам обращаться?')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол клиента')),
                ('preferred_psychologist_age', models.CharField(choices=[('AGE_18_25', 'От 18 до 25'), ('AGE_25_35', 'От 25 до 35'), ('AGE_35_PLUS', 'От 35')], max_length=20, verbose_name='Возраст специалиста')),
                ('psychologist_gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол специалиста')),
                ('psychologist_language', models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=10, verbose_name='Язык общения')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('comments', models.TextField(verbose_name='Комментарий')),
                ('client_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('telegram_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Telegram ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONTACTED', 'Психолог связался'), ('COMPLETED', 'Сессия проведена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название темы')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('communication_language', models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=10, null=True, verbose_name='Язык общения')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='psychologist_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс психолога')),
                ('is_in_catalog', models.BooleanField(default=False)),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ailaq.psychologistapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('psychologist_name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ailaq.quickclientconsultationrequest')),
                ('session_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ailaq.psychologistsessionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='ailaq.psychologistapplication')),
            ],
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='psychologist_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_documents', to='ailaq.psychologistapplication'),
        ),
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_consultations', to='ailaq.psychologistprofile', verbose_name='Принята психологом'),
        ),
        migrations.AddField(
            model_name='psychologistsessionrequest',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailaq.psychologistprofile'),
        ),
        migrations.AddField(
            model_name='psychologistsessionrequest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_requests', to='ailaq.psychologistprofile'),
        ),
        migrations.CreateModel(
            name='BuyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='ailaq.clientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='ailaq.psychologistprofile')),
            ],
        ),
    ]
