# Generated by Django 4.2.17 on 2025-01-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='catalog_description_ru',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='middle_name_ru',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='session_discount',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='session_price',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='specializations',
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ailaq.psychologistapplication'),
        ),
    ]
