# Generated by Django 4.2.18 on 2025-03-09 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickClientConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Как к вам обращаться?')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол')),
                ('preferred_psychologist_age', models.CharField(choices=[('18-25', 'От 18 до 25'), ('25-35', 'От 25 до 35'), ('35+', 'От 35')], max_length=20, verbose_name='Возраст специалиста')),
                ('psychologist_gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол специалиста')),
                ('psychologist_language', models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=10, verbose_name='Язык общения')),
                ('topic', models.CharField(max_length=255, verbose_name='Основная тема')),
                ('comments', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Код подтверждения')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID клиента')),
                ('additional_topics', models.ManyToManyField(related_name='consultations', to='ailaq.topic', verbose_name='Дополнительные темы')),
            ],
        ),
        migrations.RenameField(
            model_name='psychologistapplication',
            old_name='child_psychologist_directions',
            new_name='additional_psychologist_directions',
        ),
        migrations.RenameField(
            model_name='psychologistapplication',
            old_name='practice_start_date',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='age',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='coach_directions',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='couple_online_session_discount',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='couple_online_session_duration',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='couple_online_session_price',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='couple_session_discount',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='couple_session_duration',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='couple_session_price',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='help_text_ru',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='online_session_discount',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='online_session_duration',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='online_session_price',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='passport_document',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='psychologist_directions',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='session_discount',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='session_price',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='work_features',
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='title',
            field=models.CharField(blank=True, help_text='Название документа', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Год получения документа', null=True),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж работы (в годах)'),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='service_cities',
            field=models.JSONField(blank=True, default=list, help_text='Список городов приема'),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='service_countries',
            field=models.JSONField(blank=True, default=list, help_text='Список стран приема'),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='service_sessions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='communication_language',
            field=models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='education_files',
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('OTHER', 'Другой')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='office_address',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес офиса'),
        ),
        migrations.DeleteModel(
            name='QuickConsultationRequest',
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='education_files',
            field=models.ManyToManyField(blank=True, related_name='applications', to='ailaq.educationdocument'),
        ),
    ]
