# Generated by Django 4.2.20 on 2025-04-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistapplication',
            name='previous_rejection_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к отклонению'),
        ),
    ]
