# Generated by Django 4.2.17 on 2025-01-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='is_verified',
        ),
    ]
