# Generated by Django 4.2.17 on 2025-03-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='quickclientconsultationrequest',
            name='verification_code',
        ),
    ]
