# Generated by Django 4.2.17 on 2025-01-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0002_remove_psychologistprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
