# Generated by Django 4.2.17 on 2025-03-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0002_remove_clientprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='client_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
