# Generated by Django 4.2.20 on 2025-04-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0002_psychologistapplication_previous_rejection_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='communication_language',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='additional_psychologist_directions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='additional_specialization',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='communication_language',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='problems_worked_with',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='qualification',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='work_methods',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='works_with',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
