# Generated by Django 4.2.18 on 2025-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0002_quickclientconsultationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол клиента'),
        ),
    ]
