# Generated by Django 4.2.17 on 2025-03-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0003_quickclientconsultationrequest_client_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='phone_number',
        ),
    ]
