# Generated by Django 4.2.20 on 2025-03-30 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0003_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('telegram_id', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONTACTED', 'Психолог связался'), ('COMPLETED', 'Сессия проведена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=20)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailaq.psychologistprofile')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_requests', to='ailaq.psychologistprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='client',
        ),
        migrations.RemoveField(
            model_name='session',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='session',
        ),
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('CONTACTED', 'Психолог связался'), ('COMPLETED', 'Сессия проведена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='consultation_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ailaq.quickclientconsultationrequest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PurchasedRequest',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='review',
            name='session_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ailaq.psychologistsessionrequest'),
        ),
    ]
