# Generated by Django 4.2.20 on 2025-04-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0003_remove_psychologistapplication_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologistsessionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на сессию', 'verbose_name_plural': 'Заявки на сессию'},
        ),
        migrations.AddField(
            model_name='psychologistsessionrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_requests', to='ailaq.clientprofile', verbose_name='Клиентский профиль'),
        ),
        migrations.AddField(
            model_name='psychologistsessionrequest',
            name='review_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologistsessionrequest',
            name='review_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests_received', to='ailaq.psychologistprofile', verbose_name='Психолог'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('CONTACTED', 'Психолог связался'), ('COMPLETED', 'Сессия проведена'), ('CANCELED', 'Отменена')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_requests', to='ailaq.psychologistprofile', verbose_name='Принята психологом'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='telegram_id',
            field=models.CharField(max_length=100, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='psychologistsessionrequest',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Тема запроса'),
        ),
    ]
