# Generated by Django 5.1.7 on 2025-03-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0003_alter_quickclientconsultationrequest_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('OTHER', 'Другой')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='preferred_psychologist_age',
            field=models.CharField(choices=[('AGE_18_25', 'От 18 до 25'), ('AGE_25_35', 'От 25 до 35'), ('AGE_35_PLUS', 'От 35')], max_length=20, verbose_name='Возраст специалиста'),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='psychologist_gender',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('OTHER', 'Другой')], max_length=10, verbose_name='Пол специалиста'),
        ),
    ]
