# Generated by Django 5.1.7 on 2025-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0004_alter_psychologistapplication_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistapplication',
            name='communication_language',
            field=models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='psychologist_gender',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол специалиста'),
        ),
    ]
