# Generated by Django 4.2.17 on 2025-03-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0004_remove_psychologistapplication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_consultations', to='ailaq.psychologistprofile', verbose_name='Принята психологом'),
        ),
        migrations.AddField(
            model_name='session',
            name='review_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='review_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
