# Generated by Django 4.2.20 on 2025-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0004_alter_psychologistsessionrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='psychologist_gender',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Пол специалиста'),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='psychologist_language',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Язык общения'),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='topic',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Тема'),
        ),
    ]
