# Generated by Django 4.2.17 on 2025-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0005_quickclientconsultationrequest_taken_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
