# Generated by Django 5.1.7 on 2025-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0005_alter_psychologistapplication_communication_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='communication_language',
            field=models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KZ', 'Казахский')], max_length=10, null=True, verbose_name='Язык общения'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Фото профиля'),
        ),
    ]
