# Generated by Django 4.2.20 on 2025-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0005_alter_quickclientconsultationrequest_psychologist_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='preferred_psychologist_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст специалиста'),
        ),
    ]
