# Generated by Django 4.2.17 on 2025-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0006_clientprofile_birth_date_clientprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
