# Generated by Django 4.2.20 on 2025-04-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0006_alter_quickclientconsultationrequest_preferred_psychologist_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickclientconsultationrequest',
            name='preferred_psychologist_age',
        ),
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='preferred_psychologist_age_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='preferred_psychologist_age_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
