# Generated by Django 4.2.17 on 2025-04-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0004_psychologistsessionrequest_remove_session_client_and_more'),
        ('ailaq', '0006_customuser_username'),
    ]

    operations = [
    ]
