# Generated by Django 4.2.17 on 2025-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0007_remove_clientprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickclientconsultationrequest',
            name='additional_topics',
        ),
        migrations.RemoveField(
            model_name='quickclientconsultationrequest',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='quickclientconsultationrequest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
    ]
