# Generated by Django 4.2.20 on 2025-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0007_remove_quickclientconsultationrequest_preferred_psychologist_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologistapplication',
            old_name='additional_specialization',
            new_name='children_psychologist_directions',
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='associations_memberships',
            field=models.JSONField(blank=True, default=list, help_text='Список ассоциаций', null=True),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='coach_directions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='psychiatrist_directions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='service_cities',
            field=models.CharField(blank=True, help_text='Список городов приема', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistapplication',
            name='service_countries',
            field=models.CharField(blank=True, help_text='Список стран приема', max_length=255, null=True),
        ),
    ]
