# Generated by Django 4.2.17 on 2025-04-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0007_merge_20250402_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistapplication',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='psychologists/', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='psychologists_profiles/', verbose_name='Фото профиля'),
        ),
    ]
