# Generated by Django 4.2.20 on 2025-04-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0008_rename_additional_specialization_psychologistapplication_children_psychologist_directions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologistapplication',
            old_name='children_psychologist_directions',
            new_name='additional_specialization',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='coach_directions',
        ),
        migrations.RemoveField(
            model_name='psychologistapplication',
            name='psychiatrist_directions',
        ),
    ]
