# Generated by Django 4.2.17 on 2025-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0008_remove_quickclientconsultationrequest_additional_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='quickclientconsultationrequest',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Telegram ID'),
        ),
    ]
