# Generated by Django 4.2.20 on 2025-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0009_rename_children_psychologist_directions_psychologistapplication_additional_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistapplication',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='psychologistapplication',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
