# Generated by Django 4.2.17 on 2025-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailaq', '0009_alter_customuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdocument',
            name='file_signature',
            field=models.CharField(blank=True, help_text='Подпись к файлу', max_length=255, null=True),
        ),
    ]
